// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppConfig {
    "taskKey": string;
    "cacheDir": string;
    "cacheLimitGB": number;
    "bounds": { [_ in string]?: WindowBounds } | null;
    "backend": string;
    "stream": string;
    "version": string;
}

export interface AudioResult {
    "path": string;
    "size": number;
}

export interface CacheMigrationResult {
    "ok": boolean;
    "dir": string;
    "moved": number;
    "kept": number;
}

export interface CacheStats {
    "bytes": number;
    "files": number;
    "limitBytes": number;
    "dir": string;
}

export interface Clip {
    "id": string;
    "name": string;
    "t0": number;
    "t1": number;
    "createdAt": number;
}

export interface CloudLibraryEntry {
    "video_id": string;
    "title": string;
    "fp": string;
    "created_at": number;
}

export interface DownloadResult {
    "ok": boolean;
}

export interface ExportOptions {
    "id": string;
    "t0": number;
    "t1": number;
    "ass": string;
    "crf": number;
    "preset": string;
    "scaleH": number;
    "abr": string;
    "outPath": string;
}

export interface ExportResult {
    "ok": boolean;
    "path": string;
    "size": number;
}

export interface FFmpegStatus {
    "state": string;
    "version": string;
    "path": string;
    "done": number;
    "total": number;
    "error": string;
}

export interface HomeNotice {
    "error": string;
    "unauthorized": boolean;
}

export interface HomeProbe {
    "ready": boolean;
    "state": string;
    "cards": number;
    "error": string;
}

export interface ImportFailure {
    "path": string;
    "name": string;
    "error": string;
}

export interface ImportResult {
    "added": LibraryEntry[] | null;
    "failed": ImportFailure[] | null;
}

export interface LibraryEntry {
    "id": string;
    "srcPath": string;
    "title": string;
    "size": number;
    "duration": number;
    "width": number;
    "height": number;
    "fp": string;
    "addedAt": number;
    "lastAccess": number;
    "clips"?: Clip[] | null;
    "cloudOnly"?: boolean;
}

export interface LibraryRemoveOptions {
    "cache": boolean;
    "thumb": boolean;
    "entry": boolean;
}

export interface MediaMetadata {
    "duration": number;
    "width": number;
    "height": number;
    "hasVideo": boolean;
    "hasAudio": boolean;
}

export interface MediaProgress {
    "id": string;
    "stage": string;
    "done": number;
    "total": number;
}

export interface PeaksResult {
    "per_sec": number;
    "duration": number;
    "peaks": number[] | null;
}

export interface PlaybackProbe {
    "ready": boolean;
    "seeked": boolean;
    "duration": number;
    "currentTime": number;
    "width": number;
    "height": number;
    "error": string;
}

export interface ReleaseNotes {
    "version": string;
    "notes": string;
}

export interface RuntimeInfo {
    "goVersion": string;
    "wailsVersion": string;
    "platform": string;
    "processId": number;
    "startedAt": number;
    "uptimeMillis": number;
    "smokeMode": boolean;
}

export interface SwitchMetric {
    "kind": string;
    "millis": number;
    "sequence": number;
}

export interface ThumbReady {
    "id": string;
    "path": string;
}

export interface TranscodeResult {
    "ok": boolean;
    "url": string;
}

export interface UpdateStatus {
    "mandatory": boolean;
    "version": string;
    "stage": string;
    "done": number;
    "total": number;
    "ready": boolean;
}

export interface UploadResult {
    "ok": boolean;
    "status": number;
}

export interface VideoAttachResult {
    "ok": boolean;
    "url": string;
}

export interface VideoExpectation {
    "fp": string;
    "duration": number;
}

export interface VideoFailed {
    "id": string;
    "error": string;
}

export interface VideoInfo {
    "available": boolean;
    "name": string;
    "size": number;
    "modifiedAt": string;
    "url": string;
}

export interface VideoReady {
    "id": string;
    "url": string;
}

export interface VideoResolution {
    "state": string;
    "url"?: string;
    "reason"?: string;
}

export interface VideoResolveOptions {
    "canR2": boolean;
}

export interface VideoSelection {
    "canceled"?: boolean;
    "ok"?: boolean;
    "path"?: string;
    "warn"?: string;
}

export interface WindowBounds {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximized": boolean;
    "fullScreen": boolean;
}
