// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as app$0 from "../../../../../online.nonoka.subtitle/desktop/internal/app/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "ffmpeg:status": app$0.FFmpegStatus;
            "files:dropped": string[] | null;
            "home:refresh": app$0.HomeNotice;
            "library:changed": app$0.LibraryEntry[] | null;
            "media:progress": app$0.MediaProgress;
            "prototype:request-close": string;
            "prototype:switch": app$0.SwitchMetric;
            "prototype:video": app$0.VideoInfo;
            "thumb:ready": app$0.ThumbReady;
            "update:ready": { [_ in string]?: string } | null;
            "update:status": app$0.UpdateStatus;
            "video:failed": app$0.VideoFailed;
            "video:ready": app$0.VideoReady;
        }
    }
}
