// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AttachLocalVideo(id: string, source: string): $CancellablePromise<$models.VideoAttachResult> {
    return $Call.ByID(63887408, id, source);
}

export function CacheThumbFromCloud(id: string, sourceURL: string): $CancellablePromise<boolean> {
    return $Call.ByID(659657762, id, sourceURL);
}

export function CancelMediaJob(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(3188611870, id);
}

export function ClearCache(id: string): $CancellablePromise<void> {
    return $Call.ByID(1365821754, id);
}

export function ConsumeReleaseNotes(): $CancellablePromise<$models.ReleaseNotes | null> {
    return $Call.ByID(2179049497);
}

export function CopyIntoCache(id: string, source: string): $CancellablePromise<string> {
    return $Call.ByID(4132966138, id, source);
}

export function DeleteTemp(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3048151802, path);
}

export function DownloadFromR2(id: string): $CancellablePromise<$models.DownloadResult> {
    return $Call.ByID(1669950231, id);
}

export function ExtractAudio(id: string): $CancellablePromise<$models.AudioResult> {
    return $Call.ByID(929404150, id);
}

export function FFmpegStatus(): $CancellablePromise<$models.FFmpegStatus> {
    return $Call.ByID(3957531904);
}

export function GetCacheStats(): $CancellablePromise<$models.CacheStats> {
    return $Call.ByID(1208305976);
}

export function GetClips(id: string): $CancellablePromise<$models.Clip[] | null> {
    return $Call.ByID(1969005564, id);
}

export function GetConfig(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(1560844507);
}

export function GetLibrary(): $CancellablePromise<$models.LibraryEntry[] | null> {
    return $Call.ByID(3567207380);
}

export function GetUpdateStatus(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(1729265258);
}

export function HasCache(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(388509741, id);
}

export function ImportVideos(paths: string[] | null): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1902295754, paths);
}

export function InstallUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(3206529247);
}

export function MigrateCacheDirectory(newDir: string): $CancellablePromise<$models.CacheMigrationResult> {
    return $Call.ByID(3783115341, newDir);
}

export function OpenLibraryVideo(id: string): $CancellablePromise<$models.VideoInfo> {
    return $Call.ByID(2902025237, id);
}

export function PathExists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2724183912, path);
}

export function PickAndImportVideos(): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(4152222822);
}

export function PickAndValidateVideo(id: string, expect: $models.VideoExpectation): $CancellablePromise<$models.VideoSelection> {
    return $Call.ByID(315053460, id, expect);
}

export function PickCacheDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3731482531);
}

export function PickExportOutput(defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(2116135501, defaultName);
}

export function PickVideos(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3412144494);
}

export function ProbeVideo(path: string): $CancellablePromise<$models.MediaMetadata> {
    return $Call.ByID(4169708406, path);
}

export function RemoveLibraryData(id: string, options: $models.LibraryRemoveOptions): $CancellablePromise<void> {
    return $Call.ByID(764329926, id, options);
}

export function RemoveLibraryEntry(id: string, removeCache: boolean, removeThumb: boolean): $CancellablePromise<void> {
    return $Call.ByID(2354170974, id, removeCache, removeThumb);
}

export function RenameLibraryID(oldID: string, newID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3220749485, oldID, newID);
}

export function RenameLibraryTitle(id: string, title: string): $CancellablePromise<boolean> {
    return $Call.ByID(2896347814, id, title);
}

export function RenderExport(options: $models.ExportOptions): $CancellablePromise<$models.ExportResult> {
    return $Call.ByID(1139722777, options);
}

export function ResolveVideo(id: string, options: $models.VideoResolveOptions): $CancellablePromise<$models.VideoResolution> {
    return $Call.ByID(625424184, id, options);
}

export function RetryFFmpeg(): $CancellablePromise<$models.FFmpegStatus> {
    return $Call.ByID(2742329150);
}

export function RevealInFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(2845333333, path);
}

export function SaveSubtitle(defaultName: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(114112206, defaultName, content);
}

export function SetClips(id: string, clips: $models.Clip[] | null): $CancellablePromise<boolean> {
    return $Call.ByID(3336972040, id, clips);
}

export function SetConfig(config: $models.AppConfig): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(628077783, config);
}

export function SetOpenInEditor(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(4357643, id);
}

export function SyncCloudLibrary(entries: $models.CloudLibraryEntry[] | null): $CancellablePromise<$models.LibraryEntry[] | null> {
    return $Call.ByID(1108211700, entries);
}

export function ThumbnailURL(id: string): $CancellablePromise<string> {
    return $Call.ByID(3147639070, id);
}

export function TouchCache(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(4025053572, id);
}

export function UploadFile(id: string, filePath: string, putURL: string, headers: { [_ in string]?: string } | null): $CancellablePromise<$models.UploadResult> {
    return $Call.ByID(45454804, id, filePath, putURL, headers);
}

export function UploadThumb(id: string, putURL: string): $CancellablePromise<$models.UploadResult> {
    return $Call.ByID(2622947826, id, putURL);
}
