// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseEditor(notice: $models.HomeNotice): $CancellablePromise<void> {
    return $Call.ByID(1149965706, notice);
}

export function CurrentVideo(): $CancellablePromise<$models.VideoInfo> {
    return $Call.ByID(1873583365);
}

export function DiscardAndReturn(): $CancellablePromise<void> {
    return $Call.ByID(475868520);
}

export function OpenEditor(): $CancellablePromise<void> {
    return $Call.ByID(2360678840);
}

export function Ping(value: number): $CancellablePromise<number> {
    return $Call.ByID(3362236013, value);
}

export function PlaybackStatus(): $CancellablePromise<$models.PlaybackProbe> {
    return $Call.ByID(4277006090);
}

export function ReportHomeProbe(probe: $models.HomeProbe): $CancellablePromise<void> {
    return $Call.ByID(227719454, probe);
}

export function ReportPlaybackProbe(probe: $models.PlaybackProbe): $CancellablePromise<void> {
    return $Call.ByID(3447989708, probe);
}

export function ReturnHome(): $CancellablePromise<void> {
    return $Call.ByID(3479581872);
}

export function RuntimeInfo(): $CancellablePromise<$models.RuntimeInfo> {
    return $Call.ByID(121014859);
}

export function SelectVideoAndOpen(): $CancellablePromise<$models.VideoInfo> {
    return $Call.ByID(139382341);
}

export function SetDirty(dirty: boolean): $CancellablePromise<void> {
    return $Call.ByID(1615243349, dirty);
}
